[opcache]
opcache.enable=1
opcache.enable_cli=1
opcache.memory_consumption=256
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=40000
opcache.validate_timestamps=0
opcache.revalidate_path=0
opcache.save_comments=1
opcache.enable_file_override=1

; JIT tuning for long-running Octane workers
opcache.jit=0

; Fallback in case of shared hosting quirks
opcache.use_cwd=1
